language: node_js
node_js:
- '11'
before_install:
- npm install -g npm@'^5.10.0'
- npm install -g RadonApp/radon-extension-build#$TRAVIS_BRANCH || npm install -g RadonApp/radon-extension-build#develop
install:
- neb travis:install $TRAVIS_BRANCH
- neb package:validate
- git diff --exit-code
script:
- npm run test
- npm run lint
- if [ ! -f ./Build/Coverage/lcov.info ]; then exit 1; fi
after_success:
- npm install -g coveralls
- cat ./Build/Coverage/lcov.info | coveralls
deploy:
  provider: npm
  email: ci@radon.app
  api_key:
    secure: Bki19sjO6RN3StQQc1ajVnWpgUO/WBdCM+lusjFhcI6exG4bkJvcm25k8Bn5KeVXeO1dA7EFS3rp7OkmDJ2IGsUw9gC+xNxbSJ1nMVkJkw+BOnyFpoWblPurVP7oCKMKtH7/mt6u5t6kvaYeaxzXBCYnJmpaX5c2xzzc+kAxtIkx5YZP4GCnWG3tsh4c+C9hAIhinxWvkN43zxYyHOH6p4thTx7FTnhIf4NBGH7FS+9MZeSmP9GmxBN151/0MD22foDKWfvGodP42Q8cIvLCsV+JbDOcQSUtKKYWOXEexcfr+WcKUx1ERXBYbSZoNiL3oyXDdtKNAB7qErY8hTPVlbx0ArbYwcvb//TffIeR6Bk63TlMSNGJywvXBiws/KY+UBvUtI+Umlo5F66r7wvZQdKjLNLsZEUumIhoZZ004ddlJQtjdulfxvbRt3mIEWbPyzY90SJbRgfW1VDoFIizSt1YtIbATZPIUZiRT43RQvxMHrNM8lqEaJzfRqDc2K6UMnaPh2CLspHrJxLdOMM0otcAQ2Mg/B+IHE2SFwsxmylRtuw/R8OhO89vX86MQdt8HKA4o7N2d5KsAGUBF0xSiBLcYzNuQ8sXrQUNzTjKcZENk3p7mgu7NTHZrYlYWQmFov6lSRjZl3K6caDwl7zfMY41UM17VfhhVY0ZBr54+M0=
  on:
    tags: true
    repo: RadonApp/radon-extension-framework
